name: test_app_unmigrated
description: A simple command-line application that has not yet migrated to null safety

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  test_pkg:
    path: '../test_pkg/'
  test_pkg_unmigrated:
    path: '../test_pkg_unmigrated/'

dev_dependencies:
  pedantic: ^1.9.0
