name: test_app
description: A simple command-line application.

environment:
  sdk: '>=2.10.0 <2.12.0'

dependencies:
  test_pkg:
    path: '../test_pkg/'
  test_pkg_unmigrated:
    path: '../test_pkg_unmigrated/'

dev_dependencies:
  test: ^1.16.0-nullsafety.5
