name: Dart CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mit-mit/setup-dart@v1
        with:
          channel: dev
      - name: Report version
        run: dart --version
      - name: Check migrated app 
        run: |
          cd test_app
          dart pub get
          dart analyze
          dart format --output=none --set-exit-if-changed .
          cd ..
      - name: Check unmigrated app 
        run: |
          cd test_app_unmigrated
          dart pub get
          dart analyze
          dart format --output=none --set-exit-if-changed .
          cd ..
      - name: Run tests
        run: | 
          cd test_app
          dart test
          cd ../test_app_unmigrated
          dart test
          cd ..
